### Lab Assignment 8
### John Dominguez-Trujillo

### Activity 1

## IMPORTS ESSENTIAL LIBRARIES
## PANDAS IS A LIBRARY USED FOR DATA MANIPULATION, ANALYSIS, AND DATA STRUCTURES
## STATSMODELS IS A LIBRARY USED FOR ESTIMATING STATISTICAL MODELS AND PERFORMING REGRESSION ANALYSIS, INCLUDING GENERATING REGRESSION TABLES
import pandas as pd
import statsmodels.api as sm

## LOADS DATA FROM CSV INTO A VARIABLE
## USING A URL THAT LINKS DIRECTLY TO THE CSV FILE IN MY GITHUB SO ANYONE CAN ACCESS IT
url = 'https://raw.githubusercontent.com/JohnDT-MechE/DATA-MATH-361-Lab-Assignments/main/Lab_Assignment_8/co2-emissions-vs-gdp.csv'
data = pd.read_csv(url)

## FILTERS THE DATA FOR THE YEAR 2019
data_2019 = data[data['Year'] == 2019]

## DROPS ROWS WITH MISSING VALUES IN 'ANNUAL CO₂ EMISSIONS (PER CAPITA)' AND 'GDP PER CAPITA' COLUMNS
data_2019 = data_2019.dropna(subset=['GDP per capita', 'Annual CO₂ emissions (per capita)'])

## EXTRACTS THE INDEPENDENT VARIABLE (GDP PER CAPITA) INTO X
## EXTRACTS THE DEPENDENT VARIABLE (ANNUAL CO₂ EMISSIONS (PER CAPITA)) INTO Y
X = data_2019['GDP per capita']
y = data_2019['Annual CO₂ emissions (per capita)']

## ADDS A COLUMN OF ONES TO X SO THE REGRESSION MODEL INCLUDES AN INTERCEPT TERM
X = sm.add_constant(X)

## SM.OLS FITS A LINEAR REGRESSION MODEL USING ORDINARY LEAST SQUARES
## .FIT() TRAINS THE MODEL ON THE DATA
model = sm.OLS(y, X).fit()

## PRINTS THE FULL REGRESSION TABLE TO THE OUTPUT TERMINAL
print(model.summary())
