### Lab Assignment 10
### John Dominguez-Trujillo

### Activity 1

## IMPORTS ESSENTIAL LIBRARIES
## PANDAS IS A LIBRARY USED FOR DATA MANIPULATION, ANALYSIS, AND DATA STRUCTURES
## STATSMODELS IS A LIBRARY USED FOR ESTIMATING STATISTICAL MODELS AND PERFORMING REGRESSION ANALYSIS, INCLUDING GENERATING REGRESSION TABLES
## STATS MODELS FORMULA API (SMF) ALLOWS LINEAR MODELS TO BE SPECIFIED USING R-LIKE FORMULAS SUCH AS 'INCOME ~ AGE'
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

## LOADS DATA FROM CSV INTO A VARIABLE
## USING A URL THAT LINKS DIRECTLY TO THE CSV FILE IN MY GITHUB SO ANYONE CAN ACCESS IT
url = 'https://raw.githubusercontent.com/JohnDT-MechE/DATA-MATH-361-Lab-Assignments/refs/heads/main/Lab_Assignment_10/Income.csv'
df = pd.read_csv(url)
df.head()


## 1.1 REGRESSION TABLE OF INCOME AGAINST AGE

## THIS USES STATSMODELS FORMULA API TO FIT A LINEAR REGRESSION MODEL PREDICTING INCOME BASED ON AGE
## .FIT() TRAINS THE MODEL ON THE DATA
model_age = smf.ols('Income ~ Age', data=df).fit()
print("Regression: Income ~ Age")

## PRINTS THE FULL REGRESSION TABLE TO THE OUTPUT TERMINAL
print(model_age.summary())

## PRINTS A NEW LINE TO IMPROVE READABILITY OF OUTPUT
print('\n')


## 1.2 REGRESSION TABLE OF INCOME AGAINST EXPERIENCE

## THIS USES STATSMODELS FORMULA API TO FIT A LINEAR REGRESSION MODEL PREDICTING INCOME BASED ON EXPERIENCE
## DIFFERENCE IS THAT THE PREDICTOR IS NOW EXPERIENCE
model_exp = smf.ols('Income ~ Experience', data=df).fit()
print("\nRegression: Income ~ Experience")
print(model_exp.summary())
print('\n')


## 1.3 REGRESSION TABLE OF INCOME AGAINST AGE AND EXPERIENCE

## THIS USES STATSMODELS FORMULA API TO FIT A LINEAR REGRESSION MODEL PREDICTING INCOME BASED ON AGE AND EXPERIENCE
## DIFFERENCE IS THAT THE PREDICTOR IS NOW AGE AND EXPERIENCE
model_both = smf.ols('Income ~ Age + Experience', data=df).fit()
print("\nRegression: Income ~ Age + Experience")
print(model_both.summary())

